---
collections:
  - name: arista.eos # Requires netcommon >=2.5.1
    version: v6.2.2
  - name: ansible.network # Requires utils >=2.2.0 and netcommon 2.1.0
    version: v2.0.0
  - name: ansible.netcommon # Required by network, >=2.2.0
    version: v5.3.0
  - name: ansible.utils # Second latest version, matches above reqs
    version: v2.9.0
  - name: netbox.netbox  # Does not require dependency
