---
- name: convert interface to structured data
  hosts: all
  gather_facts: no

  tasks:
    - name: load read interfaces role
      include_role:
        name: "roles/facts"

- name: build report with facts
  hosts: all
  gather_facts: no

  tasks:

    - name: build a report
      include_role:
        name: "roles/build_report"

    - name: Template information for email report
      ansible.builtin.set_fact:
        network_report: "{{ lookup('template', 'templates/report.j2') }}"

    - name: Debug fact
      ansible.builtin.debug:
          var: network_report 

    - name: Send email
      community.general.mail:
        host: smtp.gmail.com
        port: 587  # Usually 25, 465, or 587
        username: screwtherhino@gmail.com
        password: 'mahj irxk prhj ctbv'
        to: Zachary Thompson <zthompson@conres.com>
        subject: "Arista Network Report"
        body: "{{ network_report }}"
        subtype: html
        secure: starttls
      delegate_to: localhost
