---
- name: convert interface to structured data
  hosts: all
  gather_facts: no

  tasks:
    - name: Replace device configuration with provided configuration
      arista.eos.eos_acls:
      config:
        - afi: ipv4
          acls:
            - name: test1
              aces:
                - sequence: 35
                  grant: permit
                  protocol: ospf
                  source:
                    subnet_address: 20.0.0.0/8
                  destination:
                    any: true
      state: replaced

    - name: load read interfaces role
      import_role:
        name: "roles/facts"

  post_tasks:

    - name: Send email
      community.general.mail:
        host: smtp.gmail.com
        port: 587  # Usually 25, 465, or 587
        username: screwtherhino@gmail.com
        password: 'mahj irxk prhj ctbv'
        to: Zachary Thompson <zthompson@conres.com>
        subject: "Arista Network Report"
        body: "{{ lookup('template', 'templates/report_html.j2') }}"
        subtype: html
        secure: starttls
      delegate_to: localhost
      run_once: true
