---
- name: convert interface to structured data
  hosts: all
  gather_facts: no

  tasks:
    - name: load read interfaces role
      include_role:
        name: "roles/facts"

  post_tasks:

    - name: Send email
      community.general.mail:
        host: smtp.gmail.com
        port: 587  # Usually 25, 465, or 587
        username: screwtherhino@gmail.com
        password: 'mahj irxk prhj ctbv'
        to: Zachary Thompson <zthompson@conres.com>
        subject: "Arista Network Report"
        body: "{{ lookup('template', 'templates/report.j2') }}"
        subtype: html
        secure: starttls
      delegate_to: localhost
      run_once: true
