# This task will backup the configuration
- name: Export configuration
  paloaltonetworks.panos.panos_export:
    provider: '{{ provider }}'
    category: 'configuration'
    filename: 'running-config.xml'   
  register: backup_result

- name: debug output
  debug:
    var: config_output.backup_path

# This task removes the Current configuration... from the top of IOS routers show run
- name: remove non config lines - regexp
  lineinfile:
    path: "{{ config_output.backup_path }}"
    line: "Building configuration..."
    state: absent
  delegate_to: localhost
