---
- name: gather arista eos facts
  eos.facts:
    provider: "{{arista_credentials}}"
    gather_subset: config
    gather_network_resources: "{{ network_resource | default('!bgp_global,!bgp_address_family') }}"
  vars:
    network_resource: all
