---
- name: gather arista eos facts
  arista.eos.eos.facts:
    gather_subset: config
    gather_network_resources: 
      - '!bgp_global'
      - '!bgp_address_family'
  vars:
    network_resource: all
