---
- name: convert interface to structured data
  hosts: network
  gather_facts: no

  tasks:
    - name: load read interfaces role
      include_role:
        name: "../roles/facts"

- name: build report with facts
  hosts: ansible-1
  gather_facts: no

  tasks:

    - name: build a report
      include_role:
        name: "../roles/build_report"

    - name: Send email
      community.general.mail:
        host: smtp.gmail.com
        port: 587  # Usually 25, 465, or 587
        username: screwtherhino@gmail.com
        password: 'mahj irxk prhj ctbv'
        to: Zachary Thompson <zthompson@conres.com>
        subject: "Azure Network Report"
        body: "{{ report.j2 }}"
        subtype: html
        secure: starttls
